services:
  nemo:
    container_name: nemo-canary
    image: nvcr.io/nvidia/nemo:24.12.01
    runtime: nvidia 
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./workspace:/workspace
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd:/dev/snd
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]